sudo: false # allows builds to be run in a container (faster)
install: make
script: make test
language: node_js
node_js:
  - 0.8
  - 0.10
  - 0.12
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
